#!/usr/bin/env ruby
require 'mkmf'
system( "ln -sf ../melted.i" )
system( "swig -c++ -ruby -I../../melted++ `pkg-config mlt++ --cflags` melted.i" )
$CFLAGS += " -I../../melted++ `pkg-config mlt++ --cflags`"
$LDFLAGS += " -L../../melted++ -lmelted++"
create_makefile('melted')
system( 'make' )
