#!/bin/sh

path=`which tclsh 2>/dev/null`

if [ "$path" != "" ]
then
	ln -sf ../melted.i

	# Invoke swig
	swig -c++ -I../../melted++ `pkg-config mlt++ --cflags` -tcl melted.i || exit 1

	# Compile the wrapper
	g++ -D_GNU_SOURCE -c -rdynamic -pthread -I../../melted++ `pkg-config mlt++ --cflags` melted_wrap.cxx || exit 1

	# Create the module
	gcc -shared melted_wrap.o -L../../melted++ -lmelted++ -o melted.so || exit 1
else
	echo "Unable to locate tclsh."
	exit 1
fi

