#!/bin/sh

path=`which java 2> /dev/null`

if [ $? = 0 ]
then
	# Locate the path for the include
	path=`dirname $path`
	path=`dirname $path`

	# Change this as needed
	# export JAVA_INCLUDE="-I$path/include -I$path/include/linux"

	ln -sf ../melted.i

	# Invoke swig
	mkdir -p src_swig/org/mltframework
	swig -c++ -I../../melted++ `pkg-config mlt++ --cflags` -java -outdir src_swig/org/mltframework -package org.mltframework melted.i || exit $?

	# Compile the wrapper
	g++ -D_GNU_SOURCE -c -rdynamic -pthread -I../../melted++ `pkg-config mlt++ --cflags` melted_wrap.cxx $JAVA_INCLUDE || exit $?
	
	# Create the module
	gcc -shared melted_wrap.o -L../../melted++ -lmelted++ -o libmelted_java.so || exit $?

	# Compile the test
	javac `find src_swig -name '*.java'` || exit $?

	export CLASSPATH=`pwd`/src_swig
else
	echo "Java command not found"
	exit 1
fi
